### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by temujin9** [knowitall/reverb#15]
Could I encourage you to place some open source license on this? I'm interested in using this, but cannot do so without clear understanding of my legal rights to do so.

**Comment by SaulGarza** [comment]
I'm also interested in implementing this.

**Comment by afader** [comment]
http://reverb.cs.washington.edu/LICENSE.txt

**Comment by temujin9** [comment]
```
1.  ReVerb is not used for any commercial purposes, or as part of a system
which has commercial purposes.
```

This is not open source, which more or less completely kills my interest.

**Comment by schmmd** [comment]
@temujin9 yeah--I think it's unfortunate too.  It's was a requirement of the UW's at the time.  By now none of us are at the UW.  You could negotiate a license with them.
