### ISSUE TITLE
How to use our own data set for Open Information Extraction? A text corpus?

### ISSUE THREAD

**Issue by Akila94** [knowitall/reverb#17]
I have a text corpus of agriculture domain. I need to use Reverb to extract relationships between certain concepts in the corpus and use it for another purpose in java code. Is there a way to do this using java? In the readme.md file, there is a way to read a list of files under a certain directory, how can this be done using java for reverb?

**Comment by schmmd** [comment]
It looks like https://github.com/knowitall/reverb#running-reverb-on-a-list-of-files from the README answers your question exactly.
